[Disroot]
source=imaps://horin@disroot.org:993
source-cred-cmd=gopass -o disroot/mail
outgoing=smtp://horin@disroot.org:587
outgoing-cred-cmd=gopass -o disroot/mail
outgoing-cred-cmd-cache=true
check-mail=1m
copy-to=Sent
copy-to-replied=true
default=INBOX
folders-sort=INBOX

from=Horace Liu <horin@disroot.org>
cache-headers=true

carddav-source=https://horin@cloud.disroot.org/remote.php/dav/addressbooks/users/horin/contacts/
carddav-source-cred-cmd=gopass -o disroot/carddev
address-book-cmd=carddav-query -S Disroot %s

[Gmail]
source=imaps://im.liuhq%40gmail.com@imap.gmail.com:993
source-cred-cmd=gopass -o google/gmail/app_cert
outgoing=smtp://im.liuhq%40gmail.com@smtp.gmail.com:587
outgoing-cred-cmd=gopass -o google/gmail/app_cert
outgoing-cred-cmd-cache=true
check-mail=1m
folder-map=~/.config/aerc/gmail.foldermap
default=INBOX
folders-sort=INBOX
postpone=Drafts

from=Horace Liu <im.liuhq@gmail.com>
cache-headers=true

carddav-source=https://im.liuhq%40gmail.com@www.googleapis.com/carddav/v1/principals/im.liuhq@gmail.com/lists/default
carddav-source-cred-cmd=gopass -o google/gmail/app_cert
address-book-cmd=carddav-query -S Gmail %s
