[Settings]
gtk-icon-theme-name=Colloid-Nord-Dark
gtk-cursor-theme-name=Bocchi
gtk-cursor-theme-size=36
gtk-font-name=sans 11
gtk-application-prefer-dark-theme=1
gtk-decoration-layout=menu:
# gtk-im-module=fcitx
