# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.

#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio = [1, 5, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = false
sort_translit = true
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll"]

[preview]
wrap = "yes"
tab_size = 2
max_width = 1000
max_height = 1000
image_delay = 5
image_filter = "nearest"
image_quality = 75
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
  { run = '${EDITOR:-vi} "$@"', desc = "env EDITOR", block = true, for = "unix" },
]
open = [{ run = 'xdg-open "$1"', desc = "Open", for = "linux" }]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [
  { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
imv = [
  { run = 'imv "$@"', orphan = true, desc = "Open images via imv", for = "unix" },
]
imvd = [
  { run = 'imv-dir "$0"', orphan = true, desc = "Open images in directory via imv", for = "unix" },
]

[open]
rules = [
  # Text
  { mime = "text/*", use = [
    "edit",
    "reveal",
  ] },
  # Image
  { mime = "image/*", use = [
    "imv",
    "imvd",
    "reveal",
  ] },
  # Media
  { mime = "{audio,video}/*", use = [
    "play",
    "reveal",
  ] },
  # Archive
  { mime = "application/{,g}zip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/{tar,bzip*,7z*,xz,rar,zstd}", use = [
    "extract",
    "reveal",
  ] },
  # JSON
  { mime = "application/{json,ndjson}", use = [
    "edit",
    "reveal",
  ] },
  # pdf
  { mime = "application/pdf", use = [
    "open",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "reveal",
  ] },
  # Empty file
  { mime = "inode/empty", use = [
    "edit",
    "reveal",
  ] },
  # Folder
  { url = "*/", use = [
    "edit",
    "open",
    "reveal",
  ] },
  # Fallback
  { url = "*", use = [
    "edit",
    "open",
    "reveal",
  ] },
]

[tasks]
bizarre_retry = 5
image_alloc = 536870912  # 512MB
image_bound = [0, 0]
suppress_preload = false

[plugin]
prepend_fetchers = [
  { group = "mime", url = "local://*", run = "mime-ext.local", prio = "high" },
  { group = "mime", url = "remote://*", run = "mime-ext.remote", prio = "high" },
  { group = "git", url = "*/", run = "git" },
  { group = "git", url = "*", run = "git" },
]
prepend_previewers = [
  { mime = "text/*", run = "code" },
  { mime = "*/{xml,javascript,wine-extension-ini}", run = "code" },
  { mime = "application/{json,ndjson}", run = "json" },
  { mime = "image/{avif,hei?,jxl,svg+xml}", run = "magick" },
  { mime = "image/*", run = "image" },
  # { mime = "video/*", run = "video" },
  # { mime = "application/pdf", run = "pdf" },
  { mime = "application/{,g}zip", run = "archive" },
  { mime = "application/{tar,bzip*,7z*,xz,rar,zstd,iso9660-image}", run = "archive" },
  { mime = "font/*", run = "font" },
  { mime = "application/ms-opentype", run = "font" },
  { mime = "inode/empty", run = "empty" },
  { url = ".bash*", run = "code" },
  { url = ".zsh*", run = "code" },
  { url = "_*", run = "code" },
  { url = "*justfile", run = "code" },
  { url = "PKGBUILD", run = "code" },
  { url = ".SRCINFO", run = "code" },
  { url = "profile", run = "code" },
  { url = "*rc", run = "code" },
  { url = "config", run = "code" },
  { url = "*.config", run = "code" },
  { url = "config.*", run = "code" },
  { url = "*.desktop", run = "code" },
  { url = "*.dict", run = "code" },
  { url = "*.history", run = "code" },
  { url = ".git*", run = "code" },
  { url = "*.theme", run = "code" },
  { url = "log", run = "code" },
  { url = "*.log", run = "code" },
  { url = "*.kdl", run = "code" },
  { url = "user-dirs.dirs", run = "code" },
]
append_previewers = [
  { url = "*/", run = "folder", sync = true },
  { url = "*", run = "file" },
]

[input]
cursor_blink = false

# cd
cd_title = "Change directory:"
cd_origin = "bottom-left"
cd_offset = [0, -1, 50, 3]

# create
create_title = ["Create:", "Create (dir):"]
create_origin = "bottom-left"
create_offset = [0, -1, 50, 3]

# rename
rename_title = "Rename:"
rename_origin = "hovered"
rename_offset = [0, 1, 50, 3]

# filter
filter_title = "Filter:"
filter_origin = "bottom-left"
filter_offset = [0, -1, 50, 3]

# find
find_title = ["Find next:", "Find previous:"]
find_origin = "bottom-left"
find_offset = [0, -1, 50, 3]

# search
search_title = "Search via {n}:"
search_origin = "bottom-left"
search_offset = [0, -1, 50, 3]

# shell
shell_title = ["Shell:", "Shell (block):"]
shell_origin = "bottom-left"
shell_offset = [0, -1, 50, 3]

[confirm]
# trash
trash_title = "Trash {n} selected file{s}?"
trash_origin = "center"
trash_offset = [0, 0, 70, 20]

# delete
delete_title = "Permanently delete {n} selected file{s}?"
delete_origin = "center"
delete_offset = [0, 0, 70, 20]

# overwrite
overwrite_title = "Overwrite file?"
overwrite_origin = "center"
overwrite_offset = [0, 0, 50, 15]

# quit
quit_title = "Quit?"
quit_origin = "center"
quit_offset = [0, 0, 50, 15]

[pick]
open_title = "Open with:"
open_origin = "hovered"
open_offset = [0, 1, 50, 7]

[which]
sort_by = "none"
sort_sensitive = false
sort_reverse = false
sort_translit = true
