[Settings]
gtk-icon-theme-name=Colloid-Dark
gtk-cursor-theme-name=Bocchi
gtk-cursor-theme-size=36
gtk-font-name=sans 11
gtk-application-prefer-dark-theme=1
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_SMALL_TOOLBAR
gtk-button-images=0
gtk-menu-images=0
gtk-decoration-layout=menu:
# gtk-im-module=fcitx
