### base
terminal = yes
msg-color = yes
idle = once
keep-open = yes
taskbar-progress = no
border = no
title-bar = no
force-window=immediate
audio-display=embedded-first

monitoraspect = 16:9
autofit-larger = 100%x100%
geometry = 50%:50% 

cursor-autohide = 3000
input-builtin-bindings = no

hr-seek-framedrop = no

save-position-on-quit = yes
watch-later-options = start,vid,aid,sid,volume

demuxer-max-bytes = 1024MiB
demuxer-max-back-bytes = 512MiB

### osc
# osc = no
osd-bar = no
osd-font = "Maple Mono NF CN"
osd-font-size = 20

### video
vo = gpu-next
gpu-context = auto
hwdec = nvdec,auto-safe
# hwdec = nvdec-copy,auto-copy-safe  # post vf
hwdec-codecs = h264,hevc,vp8,vp9,av1
video-output-levels = full

### audio
# ao = jack,pipewire,alsa
ao = pipewire,alsa
volume = 100
volume-max = 130
audio-channels = auto-safe
# audio-channels = auto
audio-file-auto = fuzzy

### subtitles
sub-auto = exact
sub-file-paths = sub:subtitles
slang = chs,sc,zh-cn,chi,zh,zh-tw,cht,zho,ze
subs-fallback = yes

### screenshot
screenshot-format = png
screenshot-png-compression = 4
screenshot-template = "~/media/pictures/MPV-%P-N%n"

### colorscheme
### Main mpv options
background-color='#2E3440'
osd-back-color='#3B4252'
osd-border-color='#4C566A'
osd-color='#D8DEE9'
osd-shadow-color='#2E3440'

### Stats script options
### Options are on separate lines for clarity
### Colors are in #BBGGRR format
script-opts-append=stats-border_color=3B4252
script-opts-append=stats-font_color=ECEFF4
script-opts-append=stats-plot_bg_border_color=81A1C1
script-opts-append=stats-plot_bg_color=2E3440
script-opts-append=stats-plot_color=88C0D0

### External script options
### It is fine to leave these here even if one does not use these scripts because they are just ignored unless a script uses them

### UOSC options
script-opts-append=uosc-color=foreground=88C0D0,foreground_text=2E3440,background=2E3440,background_text=D8DEE9,curtain=2E3440,success=A3BE8C,error=BF616A

include = "~~/profiles.conf"
